sudo: false

os:
  - linux

language: node_js

node_js:
  - '10'

cache:
  directories:
    - node_modules

before_script:
  - node --version

services:
  - docker

script:
  - docker build -t alicfeng/team_standard:latest -f Dockerfile .
  - docker push alicfeng/team_standard:latest
